name: ChunkClaim
main: xyz.bytemonkey.securochunk.ChunkClaim
version: 1.2.0
author: [schmidtbochum, ByteMonkey]
depend: [Vault]
softdepend: [Multiverse-Core]
description: Chunk Protection
commands:
  chunk:
    description: Displays information about the chunk.
    permission: chunkclaim.claim
    usage: "/chunk [claim|abandon|trust|untrust]"