name: ChunkClaim
main: com.github.schmidtbochum.chunkclaim.ChunkClaim
version: 1.0.1
author: schmidtbochum
softdepend: [Multiverse-Core]
description: >
             Chunk Protection
commands:
  chunk:
    description: Displays information about the chunk.
    permission: chunkclaim.claim
    usage: "/chunk [credits|abandon|trust|untrust]"
permissions:
  chunkclaim.claim:
    description: Claim chunks.
    default: op
  chunkclaim.admin:
    description: Ignore chunk ownership, manage chunks.
    default: op